### ISSUE TITLE
what the sentence content objective actually is?

### ISSUE THREAD

**Issue by shuiqinggang** [tuvuumass/SCoPE#1]
In the ACL paper, Encouraging Paragraph Embeddings to Remember  Sentence Identity Improves Classification, you say that you pre-train the CNN-SC with sentence content objective. **But I don't figure out what is sentence content objective at all.** I wish you could detailedly explain it further, such as in the form of formula or picture or some reference reading? Thank you very much.
The chinese version of the issue is that: 您在ACL的论文中提到了您使用sentence content objective 进行预训练，同时提供了一张图片进行说明。但是对于它的详细细节并没有展开，所以我想请您针对这个sentence content objective 进行更进一步的说明，以公式、图片、推荐阅读的方式？十分感谢您的帮助。

**Comment by tuvuumass** [comment]
Hey @shuiqinggang! Thanks for the question. It means that we pretrained the paragraph encoder on the sentence content task, i.e., given the representations of a paragraph and a sentence (encoded separately by the paragraph encoder) identify whether or not the sentence appears in the paragraph.

**Comment by shuiqinggang** [comment]
Thanks for you prompt and precise reply !
